### PR TITLE
fix: source and context not passed to callable transformer

### LINKED ISSUE #191: Source and context parameters not passed to transformer ?
Hi all,

following the documentation I tried a static callback transformer. This is the simple code :

```php
<?php

require __DIR__.'/vendor/autoload.php';

use AutoMapper\Attribute\MapFrom;
use AutoMapper\AutoMapper;

class Source
{
    public ?int $id = null;
}

class Target
{
    #[MapFrom(source: Source::class, transformer: [self::class, 'transformId'])]
    public ?string $id = null;

    public static function transformId(int $id, Source $source, array $context): string
    {
        return 'https://example.com/' . $id;
    }
}
$automapper = AutoMapper::create();

$source = new Source();
$source->id = 42;

$target = $automapper->map($source, new Target());
```

But I have the following error

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Target::transformId(), 1 passed in [...]\vendor\jolicode\automapper\src\Loader\EvalLoader.php(36) : eval()'d code on line 19 and exactly 3 expected in [...]\index.php on line 18
```
It seems like Source and context are not sent to the transformer like the doc says.

Did I miss something ?

Thank you

### PR DESCRIPTION
**Pull request by MrMeshok**
Fixes #191

### CODE REVIEW

**Review by Korbeil — APPROVED** [review]
Looks good, could you add a test to validate the test ? :pray:

**Comment by MrMeshok** [comment]
It's already should be tested, because class Bar is used in generic MapTo/MapFrom tests

**Comment by Korbeil** [comment]
I mean, it should fail if it is tested, you didn't change a test in this pull request and clearly it didn't failed before.

**Comment by MrMeshok** [comment]
I changed `tests/Fixtures/MapTo/Bar.php` now `transformC` and `transformDStatic` requires source and context. Also I added `transformer: 'htmlspecialchars'` to $form property so usage of internal functions tested too. Without fix in `CallableTransformer` test will fail with this additions to `Bar`

**Review by Korbeil — APPROVED** [review]
Thanks for the test and your contribution! @MrMeshok 🙏

**Pull request merged**
